# Generated by Django 4.1.2 on 2022-10-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
            ],
        ),
    ]
