# Generated by Django 4.1.2 on 2022-10-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAPI',
            fields=[
                ('temperature', models.IntegerField(default=0, verbose_name='Temperature')),
                ('wind_speed', models.IntegerField(default=0, verbose_name='Wind_speed')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_id', models.IntegerField(default=0, verbose_name='Location_Id')),
                ('date', models.CharField(max_length=30, verbose_name='Date')),
            ],
        ),
    ]
