# Generated by Django 4.1.2 on 2022-10-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('temperature', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location_id', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
