# Generated by Django 4.1.2 on 2022-10-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherAPI', '0002_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='humidity',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
